trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployADF
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: '<your-azure-service-connection>'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying ADF pipeline..."
                bash azure/deploy_adf.sh
